// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv57ySDdCr7vPnmCwY-mrQrw_EUah8tC4',
    appId: '1:1075052199536:web:915fd29717e8e7e5f07eb5',
    messagingSenderId: '1075052199536',
    projectId: 'madprojectzulli',
    authDomain: 'madprojectzulli.firebaseapp.com',
    storageBucket: 'madprojectzulli.firebasestorage.app',
    measurementId: 'G-V1Q2Z4HBWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7FUSWsGgwxswqA_IeLSKR3uGmCibLfNM',
    appId: '1:1075052199536:android:c0bce969848b1f1af07eb5',
    messagingSenderId: '1075052199536',
    projectId: 'madprojectzulli',
    storageBucket: 'madprojectzulli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSnPvp5zJHw4iqdVZIV6Iac6jsD9ClOus',
    appId: '1:1075052199536:ios:69570a7a898d070af07eb5',
    messagingSenderId: '1075052199536',
    projectId: 'madprojectzulli',
    storageBucket: 'madprojectzulli.firebasestorage.app',
    iosBundleId: 'com.example.foodWasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSnPvp5zJHw4iqdVZIV6Iac6jsD9ClOus',
    appId: '1:1075052199536:ios:69570a7a898d070af07eb5',
    messagingSenderId: '1075052199536',
    projectId: 'madprojectzulli',
    storageBucket: 'madprojectzulli.firebasestorage.app',
    iosBundleId: 'com.example.foodWasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv57ySDdCr7vPnmCwY-mrQrw_EUah8tC4',
    appId: '1:1075052199536:web:14d7bdf56ae13782f07eb5',
    messagingSenderId: '1075052199536',
    projectId: 'madprojectzulli',
    authDomain: 'madprojectzulli.firebaseapp.com',
    storageBucket: 'madprojectzulli.firebasestorage.app',
    measurementId: 'G-4WQ4PG99D7',
  );

}